-- Clear existing bus routes
DELETE FROM bus_routes;

-- Insert all 44 bus routes
INSERT INTO bus_routes (service_id, origin, destination, stops) VALUES
('XG431', 'Ferrol E.F.', 'Ortigueira E.F.', ARRAY['Ferrol E.F.', 'Narón', 'Neda', 'Fene', 'Cabanas', 'Pontedeume', 'Miño', 'Betanzos', 'Curtis', 'Ortigueira E.F.']),
('XG432', 'Cerdido E.F.', 'Ferrol E.F.', ARRAY['Cerdido E.F.', 'San Sadurniño', 'Moeche', 'Narón', 'Ferrol E.F.']),
('XG433', 'Ferrol E.F.', 'San Sadurniño E.F.', ARRAY['Ferrol E.F.', 'Narón', 'Neda', 'San Sadurniño E.F.']),
('XG434', 'Ferrol E.F.', 'Xuvia E.F.', ARRAY['Ferrol E.F.', 'O Alto do Castiñeiro', 'Narón', 'Xuvia E.F.']),
('XG63500101', 'Ferrol E.A.', 'Hospital da Costa (Burela)', ARRAY['Ferrol E.A.', 'Narón', 'Xuvia', 'San Sadurniño', 'Moeche', 'Ortigueira', 'Espasante', 'O Barqueiro', 'Viveiro', 'Covas', 'Celeiro', 'Burela (Hospital da Costa)']),
('XG64000101', 'Praza de Galicia', 'Cedeira E.A.', ARRAY['Praza de Galicia', 'A Gándara', 'Alto do Castiñeiro', 'Polígono Río do Pozo', 'Valdoviño', 'Meirás', 'Cedeira E.A.']),
('XG64000201', 'Praza de Galicia', 'Praia da Frouxeira → Cedeira E.A.', ARRAY['Praza de Galicia', 'A Gándara', 'Polígono Río do Pozo', 'Porta do Sol (Concello)', 'Praia da Frouxeira', 'Valdoviño', 'Cedeira E.A.']),
('XG64000301', 'Praza de Galicia', 'Vilaboa', ARRAY['Praza de Galicia', 'Narón', 'O Alto do Castiñeiro', 'Río do Pozo', 'Vilaboa']),
('XG64001701', 'Praza de Galicia', 'Castro → Praia da Frouxeira', ARRAY['Praza de Galicia', 'Castro', 'Porta do Sol (Concello)', 'Praia da Frouxeira']),
('XG64001801', 'Praza de Galicia', 'Sedes → Praia da Frouxeira', ARRAY['Praza de Galicia', 'Sedes', 'Porta do Sol (Concello)', 'Praia da Frouxeira']),
('XG64001901', 'Praza de Galicia', 'Praia da Frouxeira', ARRAY['Praza de Galicia', 'Avenida de Esteiro', 'Río do Pozo', 'Sedes', 'Porta do Sol (Concello)', 'Praia da Frouxeira']),
('XG64002001', 'Praza de Galicia', 'Polígono Río do Pozo', ARRAY['Praza de Galicia', 'Avenida de Esteiro', 'O Feal', 'Río do Pozo']),
('XG64002401', 'Cedeira E.A.', 'Ferrol E.A.', ARRAY['Cedeira E.A.', 'Esteiro', 'Vilarrube', 'Pantín', 'Marnela', 'Porta do Sol', 'Lago', 'Sequeiro', 'Castro', 'Concello de Narón', 'Ferrol E.A.']),
('XG64003001', 'Praza de Galicia', 'Cedeira E.A.', ARRAY['Praza de Galicia', 'Narón', 'Polígono As Lagoas', 'Río do Pozo', 'Meirás', 'Pantín', 'Cedeira E.A.']),
('XG64003101', 'Praza de Galicia', 'Praia da Frouxeira → Cedeira E.A.', ARRAY['Praza de Galicia', 'San Mateo', 'Meirás', 'Taraza', 'Praia da Frouxeira', 'Pantín', 'Cedeira E.A.']),
('XG64003201', 'Cedeira E.A.', 'Ferrol E.A.', ARRAY['Cedeira E.A.', 'Esteiro', 'Vilarrube', 'Ariño', 'Pantín', 'Marnela', 'Lago', 'Sequeiro', 'Castro', 'Concello de Narón', 'Ferrol E.A.']),
('XG64003301', 'Praza de Galicia', 'Praia de Pantín → Cedeira E.A.', ARRAY['Praza de Galicia', 'Río do Pozo', 'Pantín', 'Ariño', 'Cedeira E.A.']),
('XG64003501', 'Ferrol E.A.', 'Cedeira E.A.', ARRAY['Ferrol E.A.', 'Narón', 'Castro', 'Praia da Frouxeira', 'Pantín', 'Cedeira E.A.']),
('XG64003601', 'Praza de Galicia', 'Vilaboa', ARRAY['Praza de Galicia', 'San Mateo', 'Meirás', 'Taraza', 'Lago', 'Porta do Sol', 'Coval', 'Loira', 'Vilaboa']),
('XG64003701', 'Praza de Galicia', 'Praia da Frouxeira', ARRAY['Praza de Galicia', 'Narón', 'Xubia', 'Sedes', 'Porta do Sol', 'Praia da Frouxeira']),
('XG64003801', 'Ferrol E.A.', 'Cedeira E.A.', ARRAY['Ferrol E.A.', 'Avenida de Esteiro', 'Polígono As Lagoas', 'Meirás', 'Praia da Frouxeira', 'Pantín', 'Cedeira E.A.']),
('XG64100101', 'Praza de Galicia', 'As Neves', ARRAY['Praza de Galicia', 'Caranza', 'Gándara', 'Regoela', 'Piñeiros', 'Lavandeira', 'Serra', 'As Neves']),
('XG64100401', 'As Neves', 'Praza de Galicia', ARRAY['As Neves', 'A Revolta', 'Autos Paco', 'Freixeiro', 'Concello de Narón', 'Ferrol']),
('XG64100601', 'Praza de Galicia', 'As Neves', ARRAY['Praza de Galicia', 'Esteiro', 'Telleiras', 'Casa do Deporte', 'Gándara', 'Fene', 'As Neves']),
('XG64200101', 'Mercado de San Xulián', 'O Val', ARRAY['Mercado de San Xulián', 'Esteiro', 'Campus Esteiro', 'Hospital Naval', 'San Mateo', 'O Val']),
('XG64200201', 'Mercado de San Xulián', 'A Graña', ARRAY['Mercado de San Xulián', 'Esteiro', 'Campus Esteiro', 'Serantes', 'A Cabana', 'A Graña']),
('XG64200301', 'Mercado de San Xulián', 'San Felipe', ARRAY['Mercado de San Xulián', 'Serantes', 'Valón', 'Brión', 'San Felipe']),
('XG64200401', 'Mercado de San Xulián', 'Circular', ARRAY['Mercado de San Xulián', 'Serantes', 'Doniños', 'Esmelle', 'A Bailadora', 'Serantes', 'Mercado de San Xulián']),
('XG64200501', 'Hospital Novoa Santos', 'Mougá', ARRAY['Hospital Novoa Santos', 'Catabois', 'Pazos', 'Bustelo', 'Mandía', 'Vilela', 'Papoi', 'Cobas', 'Esmelle']),
('XG64200601', 'San Pablo', 'Hospital Novoa Santos', ARRAY['San Pablo', 'Sta Mariña', 'CEIP San Xoán', 'Ipanema', 'Hospital Naval', 'Hospital Novoa Santos']),
('XG64200701', 'Doniños', 'Praza de Galicia', ARRAY['Doniños', 'Esmelle', 'A Cabana', 'Canido', 'Esteiro', 'Praza de Galicia']),
('XG64200801', 'San Felipe', 'Praza de Galicia', ARRAY['San Felipe', 'Brión', 'Valón', 'Serantes', 'Campus Esteiro', 'Praza de Galicia']),
('XG64200901', 'Valón', 'Doniños', ARRAY['Valón', 'Brión', 'Liñares', 'Doniños']),
('XG64201001', 'Gándara', 'A Malata', ARRAY['Gándara', 'A Malata']),
('XG64201101', 'Caranza', 'Gándara', ARRAY['Caranza', 'Gándara']),
('XG64201201', 'Recimil', 'Gándara', ARRAY['Recimil', 'A Malata', 'Gándara']),
('XG64201301', 'Fene', 'Ferrol', ARRAY['Fene', 'Sillobre', 'Vilanova', 'Ferrol']),
('XG64201401', 'As Neves', 'Ferrol', ARRAY['As Neves', 'Lavandeira', 'Piñeiros', 'Regoela', 'San Marcos', 'Ferrol']),
('XG64201501', 'Cobas', 'Ferrol', ARRAY['Cobas', 'Confurco', 'Mandía', 'Catabois', 'Hospital Novoa Santos', 'Ferrol']),
('XG64201601', 'Serantes', 'San Xurxo', ARRAY['Serantes', 'Doniños', 'San Xurxo']),
('XG64201701', 'Sedes', 'Ferrol', ARRAY['Sedes', 'Feira do Trece', 'O Carballo', 'Valdoviño', 'Porta do Sol', 'Ferrol']),
('XG64201801', 'Ferrol', 'Moeche', ARRAY['Ferrol', 'San Sadurniño', 'Moeche']),
('XG64201901', 'Ferrol', 'Ortigueira', ARRAY['Ferrol', 'Moeche', 'Ortigueira']),
('XG64202001', 'Ferrol', 'A Barqueira', ARRAY['Ferrol', 'Moeche', 'A Barqueira']);