// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhhhxkrwwuroslfidkrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoaGh4a3J3d3Vyb3NsZmlka3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzQ0MTgsImV4cCI6MjA2OTU1MDQxOH0.q-3Ziu8e6rXZDX5RBS6U_7E3UVz_3v22pmZ1xMIsVfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});